---
title: "The Purchasing Power Parity Puzzle"
author: Fernando Agustin Falbo, Devashish Kumar, Daniela Leitch Barra

output:
  github_document:
  toc: true
---
  
Based in the Law of One Price, the basic theory concept underlying the Purchasing Power Parity is the convergence of the price levels of two countries under a common currency, however, despite its simplicity, it has been focus of strong debate sin the 1970’s. Despite how natural the mean reversal sounds, the difficulty to prove its convergence to a stationary mean has not only posed doubts over the validity of the own concept of PPP, but also over famous econometric methods, such as the unit root and cointegrartion methods. The low power of these tests has surged as a strong hypothesis, reason for what some econometricians have opted to try new methods, the most relevant, the panel data methods. The purpose of this paper is make explicit the difference of those methods in the particular context of the Purchasing Power Parity, by replicating two important papers in the field and comparing the results obtained.

Repository contains documentation to create pdf and the html versions of the paper and the actual outputs.  

HTML version: https://faf-econ.github.io/Time_Series/html_version/Time_Series_v_html.html

PDF version: https://faf-econ.github.io/Time_Series/pdf_output/Time_Series_v_pdf.pdf
