```{r adf, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# ------------------------------------------------------------------------------------------
# -- ADF Tests
# ------------------------------------------------------------------------------------------  

country_code <- NULL
order <- NULL
ro_c <- NULL
ro_se <- NULL
ADF <- NULL

for(i in 1:20){
  x <- ts(as.data.frame(rer_by_country[i]), start = c(1973, 2), end = c(1997, 4), frequency = 4) # Take every country serie
  # install.packages("dynlm")
  library(dynlm)
  lagmodel <- dynlm(d(x) ~ L(x, 1) + d(L(x, 1:12))) # Model with 12 lags
  p <- as.numeric(summary(lagmodel)$coefficients[3:14, 4]) # Storing p-values to view significance 
  a <- 12
  b <- p[a]
  while(b > 0.1){
    a <- a - 1 
    lagmodel <- dynlm(d(x) ~ L(x, 1) + d(L(x, 1:a)))
    p <- summary(lagmodel)$coefficients[3:(a + 2), 4]
    b <- p[a]
  } # This loop drop lags with no significance (10%) until find a significant lag
  library(tseries)
  adf <- adf.test(x, k = a) # ADF Test for every country, with the lag specified by the loop
  country_code[i] <- names(rer_by_country[i]) # Storing the country code
  order[i] <- a # Storing the country lag
  ro_c[i] <- round(lagmodel$coefficients[2], 3) # Storing the country coefficient
  ro_se[i] <- round((summary(lagmodel)$coefficients[, 2])[2], 3) # Storing the country standar deviation
  ADF[i] <- round(adf$p.value, 3) # Storing the country ADF 
}

cbind(country_code, order, ro_c, ro_se, ADF) %>%
  setNames(c("iso2c", "Order", "Ro", "SE", "p-Value")) %>%
  as.data.frame() %>%
  left_join(data.frame(country), by = c("country_code" = "iso2c")) %>%
  select(countries, everything(), -country_code) %>%
  setNames(c("Country", "Lag Order", "$\\rho$", "SE", "p-value")) %>%
  # Table
  kable(format = "latex", booktabs = TRUE, caption = "ADF Tests", linesep = "", align = c("l", rep("c", 4)),
        col.names = c("Country", "Lag Order", "$\\rho$", "SE", "p-value"), escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) 
```

```{r purt, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# ------------------------------------------------------------------------------------------
# -- Panel Unit Roots Test 
# ------------------------------------------------------------------------------------------  

# First, we have to create the contry groups:
q_rer_20 <- q_rer

q_rer_10 <- q_rer_20[q_rer_20$country == "BE" | q_rer_20$country == "CA" | q_rer_20$country == "FR" | 
                       q_rer_20$country == "DE" | q_rer_20$country == "IT" | q_rer_20$country == "JP" | 
                       q_rer_20$country == "NL" | q_rer_20$country == "SW" | q_rer_20$country == "ST" | 
                       q_rer_20$country == "GB",]

q_rer_6 <- q_rer_20[q_rer_20$country == "CA" | q_rer_20$country == "FR" | q_rer_20$country == "DE" |
                      q_rer_20$country == "IT" | q_rer_20$country == "JP" | q_rer_20$country == "GB",]

q_rer_EC <- q_rer_20[q_rer_20$country == "BE" | q_rer_20$country == "FR" | q_rer_20$country == "GB" |
                       q_rer_20$country == "DE" | q_rer_20$country == "IT" | q_rer_20$country == "IE" | 
                       q_rer_20$country == "NL" | q_rer_20$country == "PT" | q_rer_20$country == "ES",]

q_rer_EMS <- q_rer_20[q_rer_20$country == "BE" | q_rer_20$country == "FR" | q_rer_20$country == "FI" |
                        q_rer_20$country == "DE" | q_rer_20$country == "IT" | q_rer_20$country == "IE" | 
                        q_rer_20$country == "NL" | q_rer_20$country == "PT" | q_rer_20$country == "ES" |
                        q_rer_20$country == "AT", ]  

groups <- list("All 20" = q_rer_20, "EC" = q_rer_EC, "EMS" = q_rer_EMS, "G6" = q_rer_6, "G10" = q_rer_10) # Store all groups in a list

IPS <- NULL
MW <- NULL

for (i in 1:5){
  library(plm)
  ips <- purtest(rer ~ 1, data = groups[[i]], index = c("country", "time"), pmax = 12, exo = "intercept", test = "ips", lags = "AIC") #Pesaran Shin Test
  mw <- purtest(rer ~ 1, data = groups[[i]], index = c("country", "time"), pmax = 12, exo = "intercept", test = "madwu", lags = "AIC") # Maddala Wu Test
  IPS[i] <- round(ips$statistic$p.value, 3) # Storing IPS for every group
  MW[i] <- round(mw$statistic$p.value, 3) # Storing MW for every group
}

cbind("Sample" = names(groups), "IPS" = IPS, "MW" =MW) %>%
  # Table
  kable(format = "latex", booktabs = TRUE, caption = "Panel Unit Roots Tests", linesep = "", align = c("l", rep("c", 2))) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
